# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TipsyiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TipsyiOS
  flutter_application_path = '../result_module'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
  
  install_all_flutter_pods(flutter_application_path)

end
